project:
  type: website

website:
  title: "cosull93.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About This Site
      - href: pyspark_example.qmd
        text: PySpark Example

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true